import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Serif, Hanken_Grotesk } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Every module renderer (todoChecklist.ts, habitTracker.ts,
// labeledBox.ts, weekTitle.ts, monthTitle.ts, monthGridCore.ts,
// hourlyGridCore.ts) already references `fontFamily: "PT Serif"`
// directly in its own rendered element data — that was never actually
// wrong, just incomplete: nothing in the app had ever loaded PT Serif
// itself, so every one of those references silently fell back to
// whatever generic serif/sans the browser defaults to instead.
// Reported directly: "can you use pt serif it doesn't look like it
// right now. use it everywhere Dec-Jan too in top left" — weekTitle.ts's
// own date-range label ("DEC 31 - JAN 6") already used the same
// FONT_FAMILY constant as everything else, confirming this was one
// single root cause (the font was never registered at all), not a
// per-module inconsistency. Loading it here, the same way
// geistSans/geistMono already are, registers the real @font-face for
// the whole app — every renderer's own existing "PT Serif" reference
// then resolves correctly with no changes needed in any of them.
// weight: ["400"] only — grepped every module renderer for fontWeight
// first (none set one; everything renders at the family's own default
// weight), so there's no unused heavier weight to load.
const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400"],
});

// Sans-serif alternative for the Page Settings font switch — closest free
// Google Font to "Altivo Light" (a commercial geometric sans): wide
// letterforms, generous x-height, subtle ink traps for small-size
// legibility, loaded at its own Light (300) weight to match. See
// src/lib/theme.ts for how module renderers resolve which one to use.
const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} ${ptSerif.variable} ${hankenGrotesk.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
