-- AlterTable
ALTER TABLE "ModuleInstance" ADD COLUMN     "columnSpan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "columnStart" INTEGER,
ADD COLUMN     "rowSpan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "rowStart" INTEGER,
ALTER COLUMN "x" DROP NOT NULL,
ALTER COLUMN "y" DROP NOT NULL,
ALTER COLUMN "width" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ModuleType" ADD COLUMN     "defaultColumnSpan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "defaultRowSpan" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Page" ADD COLUMN     "gridColumns" INTEGER,
ADD COLUMN     "gridGapPx" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "gridRows" INTEGER;
